"""
Streamlit chat UI for the GenAI GitLab Handbook Chatbot.

Run locally:
    streamlit run app.py
"""
from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

import streamlit as st

from src.config import settings

if TYPE_CHECKING:
    from src.rag import RagPipeline, Source


# --- Page config -----------------------------------------------------------

st.set_page_config(
    page_title="GitLab Handbook Chatbot",
    page_icon="📘",
    layout="wide",
)


# --- Cached resources ------------------------------------------------------

@st.cache_resource(show_spinner="Loading retrieval index and pipeline...")
def get_pipeline() -> RagPipeline:
    """Build the pipeline once per session (cached across reruns)."""
    from src.rag import RagPipeline

    return RagPipeline()


def _load_index_meta() -> dict | None:
    meta_path = settings.index_dir / "meta.json"
    if not meta_path.exists():
        return None
    try:
        return json.loads(meta_path.read_text())
    except Exception:
        return None


def _index_mtime() -> str:
    p = settings.index_dir / "faiss.index"
    if not p.exists():
        return "missing"
    ts = datetime.fromtimestamp(p.stat().st_mtime, tz=timezone.utc)
    return ts.strftime("%Y-%m-%d %H:%M UTC")


def _index_ready() -> bool:
    return (
        (settings.index_dir / "faiss.index").exists()
        and (settings.index_dir / "chunks.jsonl").exists()
    )


# --- Source rendering ------------------------------------------------------

def _render_sources(sources: list[Source]) -> None:
    if not sources:
        return
    with st.expander(f"Sources ({len(sources)})", expanded=False):
        for s in sources:
            badge = "📖" if s.source == "handbook" else "🧭"
            st.markdown(
                f"{badge} **[{s.n}] [{s.title or s.url}]({s.url})**  "
                f"&nbsp;`{s.source}` &middot; similarity `{s.best_score:.2f}`"
            )


# --- Sidebar ---------------------------------------------------------------

def _render_sidebar() -> None:
    with st.sidebar:
        st.header("About")
        st.markdown(
            "This is an **unofficial** assistant that answers questions using "
            "publicly available content from GitLab's "
            "[Handbook](https://handbook.gitlab.com/handbook/) and "
            "[Direction](https://about.gitlab.com/direction/) pages."
        )
        st.divider()

        st.subheader("Index status")
        meta = _load_index_meta()
        if meta is None:
            st.error("No index found. Run `python -m src.build_index --rebuild`.")
        else:
            st.markdown(
                f"- **Pages**: {meta.get('num_pages', '?')}\n"
                f"- **Chunks**: {meta.get('num_chunks', '?')}\n"
                f"- **Embedding model**: `{meta.get('embedding_model', '?')}`\n"
                f"- **Built**: {_index_mtime()}"
            )
        st.divider()

        st.subheader("Settings")
        st.markdown(
            f"- **Chat model**: `{settings.chat_model}`\n"
            f"- **Top-K retrieval**: {settings.top_k}"
        )
        st.divider()

        if st.button("Clear chat", use_container_width=True):
            st.session_state.messages = []
            st.rerun()

        st.caption(
            "Built as a learning project. Answers are generated by an LLM and may "
            "contain inaccuracies — verify against the linked sources."
        )


# --- Chat loop -------------------------------------------------------------

def _ensure_state() -> None:
    if "messages" not in st.session_state:
        st.session_state.messages: list[dict] = []


def _render_history() -> None:
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
            if msg["role"] == "assistant" and msg.get("sources"):
                _render_sources(msg["sources"])


def _handle_user_turn(pipe: RagPipeline, user_input: str) -> None:
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    with st.chat_message("assistant"):
        sources_holder: list[Source] = []
        top_score = 0.0
        answer_text = ""

        try:
            stream = pipe.answer_stream(user_input)
            placeholder = st.empty()

            for item in stream:
                # Refusal short-circuit
                if isinstance(item, dict) and item.get("type") == "refusal":
                    answer_text = item["answer"]
                    placeholder.markdown(answer_text)
                    break

                # Metadata header — emitted before first token
                if isinstance(item, dict) and item.get("type") == "meta":
                    sources_holder = item["sources"]
                    top_score = item["top_score"]
                    continue

                if isinstance(item, dict) and item.get("type") == "done":
                    break

                # Token delta
                if isinstance(item, str):
                    answer_text += item
                    # Cursor character makes streaming feel responsive
                    placeholder.markdown(answer_text + "▌")

            placeholder.markdown(answer_text)
            _render_sources(sources_holder)

        except Exception as e:
            error_msg = (
                "Something went wrong while generating the answer. "
                "This is usually a temporary API issue — please try again in a moment."
            )
            st.error(error_msg)
            # Show the underlying error in an expander, useful for debugging
            with st.expander("Error details (for debugging)"):
                st.code(f"{type(e).__name__}: {e}")
            answer_text = error_msg
            sources_holder = []

    st.session_state.messages.append({
        "role": "assistant",
        "content": answer_text,
        "sources": sources_holder,
        "top_score": top_score,
    })


# --- Main ------------------------------------------------------------------

def main() -> None:
    _ensure_state()
    _render_sidebar()

    st.title("📘 GitLab Handbook Chatbot")
    st.caption(
        "Ask anything about GitLab's Handbook or product direction. "
        "Answers cite their sources — click to verify."
    )

    # Show a hint when the chat is empty
    if not st.session_state.messages:
        st.info(
            "Try asking:\n\n"
            "- *What are GitLab's core values?*\n"
            "- *How does GitLab handle asynchronous communication?*\n"
            "- *What is GitLab's hiring process like?*"
        )

    _render_history()

    user_input = st.chat_input("Ask a question about GitLab's handbook…")
    if user_input:
        if not _index_ready():
            st.error("No retrieval index found. Run `python -m src.build_index --rebuild` first.")
            return

        with st.spinner("Loading retrieval index..."):
            pipe = get_pipeline()
        _handle_user_turn(pipe, user_input)


if __name__ == "__main__":
    main()  
